/*
* generated by Xtext
*/
package de.wbg;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DTDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.wbg.ui.internal.DTDSLActivator.getInstance().getInjector("de.wbg.DTDSL");
	}
	
}
