package de.wbg.StringClasses;

import de.wbg.StringClasses.ChainString;
import de.wbg.dTDSL.StringDescription;
import de.wbg.dTDSL.StringDescriptionInVariable;
import de.wbg.dTDSL.StringDescriptionInner;
import de.wbg.dTDSL.StringOr;
import de.wbg.generator.DTDSLGenerator;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class ChainStringOr extends ChainString {
  public ChainStringOr(final DTDSLGenerator g) {
    super(g);
  }
  
  @Override
  public boolean handle(final int index, final StringDescriptionInner i) {
    if ((i instanceof StringOr)) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("int oldStringPosition = this.scanner.getPosition();");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("boolean optionFound = false;");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("ArrayList<Head> parsedOptions = new ArrayList<Head>();");
      _builder.newLine();
      {
        EList<StringDescriptionInVariable> _option = ((StringOr)i).getOption();
        for(final StringDescriptionInVariable o : _option) {
          _builder.append("\t\t\t");
          _builder.append("if (!optionFound)");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("{");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t");
          _builder.append("try");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t");
          _builder.append("{");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t\t");
          _builder.append("Head optionHead = new Head(\"OPTIONHEAD\");");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t\t");
          _builder.append("parse");
          EObject _eContainer = ((StringOr)i).eContainer();
          String _name = ((StringDescription) _eContainer).getName();
          _builder.append(_name, "\t\t\t\t\t");
          _builder.append("Option");
          String _name_1 = o.getName();
          String _firstUpper = StringExtensions.toFirstUpper(_name_1);
          _builder.append(_firstUpper, "\t\t\t\t\t");
          _builder.append("(optionHead);");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t\t");
          _builder.append("\t\t");
          _builder.append("optionFound = true;");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t\t");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t\t");
          _builder.append("parsedOptions.add(optionHead);");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t");
          _builder.append("}");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t");
          _builder.append("catch (ParserException e)");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t");
          _builder.append("{");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t\t");
          _builder.append("optionFound = false;");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t\t");
          _builder.append("scanner.resetToPosition(oldStringPosition);");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("\t");
          _builder.append("}");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("}");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.newLine();
        }
      }
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("//get the head form parsedOptions with max length");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("int optionIndex = -1;");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("int optionIndexLength = -1;");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("for (int i = 0; i < parsedOptions.size(); i++)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("Element el = parsedOptions.get(i);");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("if (el.getTotalLength() > optionIndexLength)");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("optionIndex = i;");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("optionIndexLength = el.getTotalLength();");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("if (optionIndex >= 0 && optionIndexLength > 0)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("Element el = parsedOptions.get(optionIndex);");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("for (Element element : el.getChildren())");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("n.addChild(element);");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("element.setParent(n);");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("el.removeChild(element);");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("else");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("throw new ParserException(\"no possible or-option found in StringDescription \\\"");
      EObject _eContainer_1 = ((StringOr)i).eContainer();
      String _descriptionName = this.getDescriptionName(_eContainer_1);
      _builder.append(_descriptionName, "\t\t\t\t");
      _builder.append("\\\"\");");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("if (!optionFound)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("throw new ParserException(\"no possible or option found in stringobject ");
      EObject _eContainer_2 = ((StringOr)i).eContainer();
      String _descriptionName_1 = this.getDescriptionName(_eContainer_2);
      _builder.append(_descriptionName_1, "\t\t\t\t");
      _builder.append("\");");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      this.setReturnValue(_builder);
      return true;
    }
    return false;
  }
}
