/*
 * generated by Xtext
 */
package de.wbg.ui.contentassist

import de.wbg.ui.contentassist.AbstractDTDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DTDSLProposalProvider extends AbstractDTDSLProposalProvider {
}
