/*
 * generated by Xtext
 */
package de.wbg;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DTDSLRuntimeModule extends de.wbg.AbstractDTDSLRuntimeModule {

}
