/*
* generated by Xtext
*/
package de.wbg;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DTDSLStandaloneSetup extends DTDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new DTDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

