/*
* generated by Xtext
*/
package de.wbg.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class DTDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class DTDSLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DTDSL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParserNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cParserNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParserNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cParserNameAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cParserTypeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cEqualsSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final Alternatives cTypeAlternatives_6_0 = (Alternatives)cTypeAssignment_6.eContents().get(0);
		private final Keyword cTypeJavaObjectKeyword_6_0_0 = (Keyword)cTypeAlternatives_6_0.eContents().get(0);
		private final Keyword cTypeStringKeyword_6_0_1 = (Keyword)cTypeAlternatives_6_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cObjDescriptionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cObjDescriptionAbstractParserRuleCall_8_0 = (RuleCall)cObjDescriptionAssignment_8.eContents().get(0);
		private final Assignment cStartAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cStartStartPointParserRuleCall_9_0 = (RuleCall)cStartAssignment_9.eContents().get(0);
		
		//DTDSL:
		//	"parserName" "=" parserName=STRING ";" "parserType" "=" type=("javaObject" | "string") ";" objDescription+=Abstract*
		//	start=StartPoint;
		public ParserRule getRule() { return rule; }

		//"parserName" "=" parserName=STRING ";" "parserType" "=" type=("javaObject" | "string") ";" objDescription+=Abstract*
		//start=StartPoint
		public Group getGroup() { return cGroup; }

		//"parserName"
		public Keyword getParserNameKeyword_0() { return cParserNameKeyword_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//parserName=STRING
		public Assignment getParserNameAssignment_2() { return cParserNameAssignment_2; }

		//STRING
		public RuleCall getParserNameSTRINGTerminalRuleCall_2_0() { return cParserNameSTRINGTerminalRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }

		//"parserType"
		public Keyword getParserTypeKeyword_4() { return cParserTypeKeyword_4; }

		//"="
		public Keyword getEqualsSignKeyword_5() { return cEqualsSignKeyword_5; }

		//type=("javaObject" | "string")
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }

		//"javaObject" | "string"
		public Alternatives getTypeAlternatives_6_0() { return cTypeAlternatives_6_0; }

		//"javaObject"
		public Keyword getTypeJavaObjectKeyword_6_0_0() { return cTypeJavaObjectKeyword_6_0_0; }

		//"string"
		public Keyword getTypeStringKeyword_6_0_1() { return cTypeStringKeyword_6_0_1; }

		//";"
		public Keyword getSemicolonKeyword_7() { return cSemicolonKeyword_7; }

		//objDescription+=Abstract*
		public Assignment getObjDescriptionAssignment_8() { return cObjDescriptionAssignment_8; }

		//Abstract
		public RuleCall getObjDescriptionAbstractParserRuleCall_8_0() { return cObjDescriptionAbstractParserRuleCall_8_0; }

		//start=StartPoint
		public Assignment getStartAssignment_9() { return cStartAssignment_9; }

		//StartPoint
		public RuleCall getStartStartPointParserRuleCall_9_0() { return cStartStartPointParserRuleCall_9_0; }
	}

	public class StartPointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StartPoint");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cBeginWithKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cBeginAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final CrossReference cBeginObjectDescriptionCrossReference_0_2_0 = (CrossReference)cBeginAssignment_0_2.eContents().get(0);
		private final RuleCall cBeginObjectDescriptionIDTerminalRuleCall_0_2_0_1 = (RuleCall)cBeginObjectDescriptionCrossReference_0_2_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cBeginAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final CrossReference cBeginStringDescriptionCrossReference_1_0_0 = (CrossReference)cBeginAssignment_1_0.eContents().get(0);
		private final RuleCall cBeginStringDescriptionIDTerminalRuleCall_1_0_0_1 = (RuleCall)cBeginStringDescriptionCrossReference_1_0_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//StartPoint:
		//	"beginWith" "=" begin=[ObjectDescription] | begin=[StringDescription] ";";
		public ParserRule getRule() { return rule; }

		//"beginWith" "=" begin=[ObjectDescription] | begin=[StringDescription] ";"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"beginWith" "=" begin=[ObjectDescription]
		public Group getGroup_0() { return cGroup_0; }

		//"beginWith"
		public Keyword getBeginWithKeyword_0_0() { return cBeginWithKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_0_1() { return cEqualsSignKeyword_0_1; }

		//begin=[ObjectDescription]
		public Assignment getBeginAssignment_0_2() { return cBeginAssignment_0_2; }

		//[ObjectDescription]
		public CrossReference getBeginObjectDescriptionCrossReference_0_2_0() { return cBeginObjectDescriptionCrossReference_0_2_0; }

		//ID
		public RuleCall getBeginObjectDescriptionIDTerminalRuleCall_0_2_0_1() { return cBeginObjectDescriptionIDTerminalRuleCall_0_2_0_1; }

		//begin=[StringDescription] ";"
		public Group getGroup_1() { return cGroup_1; }

		//begin=[StringDescription]
		public Assignment getBeginAssignment_1_0() { return cBeginAssignment_1_0; }

		//[StringDescription]
		public CrossReference getBeginStringDescriptionCrossReference_1_0_0() { return cBeginStringDescriptionCrossReference_1_0_0; }

		//ID
		public RuleCall getBeginStringDescriptionIDTerminalRuleCall_1_0_0_1() { return cBeginStringDescriptionIDTerminalRuleCall_1_0_0_1; }

		//";"
		public Keyword getSemicolonKeyword_1_1() { return cSemicolonKeyword_1_1; }
	}

	public class AbstractElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Abstract");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cObjectDescriptionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStringDescriptionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Abstract:
		//	ObjectDescription | //| ObjectHashMapDescription
		//	StringDescription;
		public ParserRule getRule() { return rule; }

		//ObjectDescription | //| ObjectHashMapDescription
		//StringDescription
		public Alternatives getAlternatives() { return cAlternatives; }

		//ObjectDescription
		public RuleCall getObjectDescriptionParserRuleCall_0() { return cObjectDescriptionParserRuleCall_0; }

		////| ObjectHashMapDescription
		//StringDescription
		public RuleCall getStringDescriptionParserRuleCall_1() { return cStringDescriptionParserRuleCall_1; }
	}

	public class StringDescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringDescription");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStringKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionStringDescriptionInnerParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		////---------------------------  String  ---------------------------
		//StringDescription:
		//	"String" name=ID ":" "{" description+=StringDescriptionInner* "}";
		public ParserRule getRule() { return rule; }

		//"String" name=ID ":" "{" description+=StringDescriptionInner* "}"
		public Group getGroup() { return cGroup; }

		//"String"
		public Keyword getStringKeyword_0() { return cStringKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//description+=StringDescriptionInner*
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }

		//StringDescriptionInner
		public RuleCall getDescriptionStringDescriptionInnerParserRuleCall_4_0() { return cDescriptionStringDescriptionInnerParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class StringDescriptionInnerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringDescriptionInner");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringOverReadParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStringKeyParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStringValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//StringDescriptionInner: //	rule+=StringRule+
		//	StringOverRead | StringKey | StringValue;
		public ParserRule getRule() { return rule; }

		////	rule+=StringRule+
		//StringOverRead | StringKey | StringValue
		public Alternatives getAlternatives() { return cAlternatives; }

		////	rule+=StringRule+
		//StringOverRead
		public RuleCall getStringOverReadParserRuleCall_0() { return cStringOverReadParserRuleCall_0; }

		//StringKey
		public RuleCall getStringKeyParserRuleCall_1() { return cStringKeyParserRuleCall_1; }

		//StringValue
		public RuleCall getStringValueParserRuleCall_2() { return cStringValueParserRuleCall_2; }
	}

	public class StringRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringRule");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringOverReadParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStringKeyParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStringValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//StringRule:
		//	StringOverRead | StringKey | StringValue;
		public ParserRule getRule() { return rule; }

		//StringOverRead | StringKey | StringValue
		public Alternatives getAlternatives() { return cAlternatives; }

		//StringOverRead
		public RuleCall getStringOverReadParserRuleCall_0() { return cStringOverReadParserRuleCall_0; }

		//StringKey
		public RuleCall getStringKeyParserRuleCall_1() { return cStringKeyParserRuleCall_1; }

		//StringValue
		public RuleCall getStringValueParserRuleCall_2() { return cStringValueParserRuleCall_2; }
	}

	public class StringOverReadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringOverRead");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//StringOverRead:
		//	STRING;
		public ParserRule getRule() { return rule; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}

	public class StringKeyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringKey");
		private final Keyword cKeyKeyword = (Keyword)rule.eContents().get(1);
		
		//StringKey:
		//	"Key";
		public ParserRule getRule() { return rule; }

		//"Key"
		public Keyword getKeyKeyword() { return cKeyKeyword; }
	}

	public class StringValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringValue");
		private final Keyword cValueKeyword = (Keyword)rule.eContents().get(1);
		
		//StringValue:
		//	"Value";
		public ParserRule getRule() { return rule; }

		//"Value"
		public Keyword getValueKeyword() { return cValueKeyword; }
	}

	public class ObjectDescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectDescription");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNodeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionObjectDescriptionInnerParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		////---------------------------  Object  ---------------------------
		////ObjectHashMapDescription:
		////	name=ID 'as' 'HashMap' ':' '{' description=ObjectHashMapDescriptionInner '}'
		////;
		////
		////ObjectHashMapDescriptionInner:
		////	
		////;
		//ObjectDescription:
		//	"Node" name=ID ":" "{" description+=ObjectDescriptionInner* "}";
		public ParserRule getRule() { return rule; }

		//"Node" name=ID ":" "{" description+=ObjectDescriptionInner* "}"
		public Group getGroup() { return cGroup; }

		//"Node"
		public Keyword getNodeKeyword_0() { return cNodeKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//description+=ObjectDescriptionInner*
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }

		//ObjectDescriptionInner
		public RuleCall getDescriptionObjectDescriptionInnerParserRuleCall_4_0() { return cDescriptionObjectDescriptionInnerParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class ObjectNodeTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectNodeType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cNodeKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cAttributeKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//ObjectNodeType:
		//	"Node" | "Attribute";
		public ParserRule getRule() { return rule; }

		//"Node" | "Attribute"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"Node"
		public Keyword getNodeKeyword_0() { return cNodeKeyword_0; }

		//"Attribute"
		public Keyword getAttributeKeyword_1() { return cAttributeKeyword_1; }
	}

	public class ObjectDescriptionInnerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectDescriptionInner");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cObjectNodeParserRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cObjectAttributeParserRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final RuleCall cObjectNextParserRuleCall_0_2 = (RuleCall)cAlternatives_0.eContents().get(2);
		private final RuleCall cObjectMaybeParserRuleCall_0_3 = (RuleCall)cAlternatives_0.eContents().get(3);
		private final RuleCall cObjectManyParserRuleCall_0_4 = (RuleCall)cAlternatives_0.eContents().get(4);
		private final RuleCall cObjectChoiceParserRuleCall_0_5 = (RuleCall)cAlternatives_0.eContents().get(5);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ObjectDescriptionInner:
		//	(ObjectNode | ObjectAttribute | ObjectNext | ObjectMaybe | ObjectMany | ObjectChoice) ";";
		public ParserRule getRule() { return rule; }

		//(ObjectNode | ObjectAttribute | ObjectNext | ObjectMaybe | ObjectMany | ObjectChoice) ";"
		public Group getGroup() { return cGroup; }

		//ObjectNode | ObjectAttribute | ObjectNext | ObjectMaybe | ObjectMany | ObjectChoice
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//ObjectNode
		public RuleCall getObjectNodeParserRuleCall_0_0() { return cObjectNodeParserRuleCall_0_0; }

		//ObjectAttribute
		public RuleCall getObjectAttributeParserRuleCall_0_1() { return cObjectAttributeParserRuleCall_0_1; }

		//ObjectNext
		public RuleCall getObjectNextParserRuleCall_0_2() { return cObjectNextParserRuleCall_0_2; }

		//ObjectMaybe
		public RuleCall getObjectMaybeParserRuleCall_0_3() { return cObjectMaybeParserRuleCall_0_3; }

		//ObjectMany
		public RuleCall getObjectManyParserRuleCall_0_4() { return cObjectManyParserRuleCall_0_4; }

		//ObjectChoice
		public RuleCall getObjectChoiceParserRuleCall_0_5() { return cObjectChoiceParserRuleCall_0_5; }

		//";"
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}

	public class ObjectAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHasAttributeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAttributesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAttributesIDTerminalRuleCall_1_0 = (RuleCall)cAttributesAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cStringMethodeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cStringMethodeStringDescriptionCrossReference_2_1_0 = (CrossReference)cStringMethodeAssignment_2_1.eContents().get(0);
		private final RuleCall cStringMethodeStringDescriptionIDTerminalRuleCall_2_1_0_1 = (RuleCall)cStringMethodeStringDescriptionCrossReference_2_1_0.eContents().get(1);
		
		////ObjectAttribute:
		////	'hasAttribute' attributes=ID 'ofType' types=Type 
		////;
		//ObjectAttribute:
		//	"hasAttribute" attributes=ID ("as" stringMethode=[StringDescription])? // 'ofType' types=[jvmTypes::JvmType | QualifiedName] 
		//;
		public ParserRule getRule() { return rule; }

		//"hasAttribute" attributes=ID ("as" stringMethode=[StringDescription])? // 'ofType' types=[jvmTypes::JvmType | QualifiedName]
		public Group getGroup() { return cGroup; }

		//"hasAttribute"
		public Keyword getHasAttributeKeyword_0() { return cHasAttributeKeyword_0; }

		//attributes=ID
		public Assignment getAttributesAssignment_1() { return cAttributesAssignment_1; }

		//ID
		public RuleCall getAttributesIDTerminalRuleCall_1_0() { return cAttributesIDTerminalRuleCall_1_0; }

		//("as" stringMethode=[StringDescription])?
		public Group getGroup_2() { return cGroup_2; }

		//"as"
		public Keyword getAsKeyword_2_0() { return cAsKeyword_2_0; }

		//stringMethode=[StringDescription]
		public Assignment getStringMethodeAssignment_2_1() { return cStringMethodeAssignment_2_1; }

		//[StringDescription]
		public CrossReference getStringMethodeStringDescriptionCrossReference_2_1_0() { return cStringMethodeStringDescriptionCrossReference_2_1_0; }

		//ID
		public RuleCall getStringMethodeStringDescriptionIDTerminalRuleCall_2_1_0_1() { return cStringMethodeStringDescriptionIDTerminalRuleCall_2_1_0_1; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class ObjectNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHasNodeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAttributesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAttributesIDTerminalRuleCall_1_0 = (RuleCall)cAttributesAssignment_1.eContents().get(0);
		private final Keyword cAsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cInnerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cInnerObjectDescriptionCrossReference_3_0 = (CrossReference)cInnerAssignment_3.eContents().get(0);
		private final RuleCall cInnerObjectDescriptionIDTerminalRuleCall_3_0_1 = (RuleCall)cInnerObjectDescriptionCrossReference_3_0.eContents().get(1);
		
		////ObjectAttribute:
		////	'hasAttribute' attributes=ID 'ofType' (types=Type | inner=[ObjectDescription])
		////;
		////ObjectNode:
		////	'hasNode' attributes=ID 'ofType' (types=Type 'as' keyword=Keyword | inner=[ObjectDescription]) ';'	
		////;
		//ObjectNode:
		//	"hasNode" attributes=ID "as" inner=[ObjectDescription];
		public ParserRule getRule() { return rule; }

		//"hasNode" attributes=ID "as" inner=[ObjectDescription]
		public Group getGroup() { return cGroup; }

		//"hasNode"
		public Keyword getHasNodeKeyword_0() { return cHasNodeKeyword_0; }

		//attributes=ID
		public Assignment getAttributesAssignment_1() { return cAttributesAssignment_1; }

		//ID
		public RuleCall getAttributesIDTerminalRuleCall_1_0() { return cAttributesIDTerminalRuleCall_1_0; }

		//"as"
		public Keyword getAsKeyword_2() { return cAsKeyword_2; }

		//inner=[ObjectDescription]
		public Assignment getInnerAssignment_3() { return cInnerAssignment_3; }

		//[ObjectDescription]
		public CrossReference getInnerObjectDescriptionCrossReference_3_0() { return cInnerObjectDescriptionCrossReference_3_0; }

		//ID
		public RuleCall getInnerObjectDescriptionIDTerminalRuleCall_3_0_1() { return cInnerObjectDescriptionIDTerminalRuleCall_3_0_1; }
	}

	public class ObjectNextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectNext");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHasNextKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAttributeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAttributeJavaCodeOrIDParserRuleCall_1_0 = (RuleCall)cAttributeAssignment_1.eContents().get(0);
		private final Keyword cAsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cObjectDesriptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cObjectDesriptionObjectDescriptionCrossReference_3_0 = (CrossReference)cObjectDesriptionAssignment_3.eContents().get(0);
		private final RuleCall cObjectDesriptionObjectDescriptionIDTerminalRuleCall_3_0_1 = (RuleCall)cObjectDesriptionObjectDescriptionCrossReference_3_0.eContents().get(1);
		
		//ObjectNext:
		//	"hasNext" attribute=JavaCodeOrID "as" objectDesription=[ObjectDescription];
		public ParserRule getRule() { return rule; }

		//"hasNext" attribute=JavaCodeOrID "as" objectDesription=[ObjectDescription]
		public Group getGroup() { return cGroup; }

		//"hasNext"
		public Keyword getHasNextKeyword_0() { return cHasNextKeyword_0; }

		//attribute=JavaCodeOrID
		public Assignment getAttributeAssignment_1() { return cAttributeAssignment_1; }

		//JavaCodeOrID
		public RuleCall getAttributeJavaCodeOrIDParserRuleCall_1_0() { return cAttributeJavaCodeOrIDParserRuleCall_1_0; }

		//"as"
		public Keyword getAsKeyword_2() { return cAsKeyword_2; }

		//objectDesription=[ObjectDescription]
		public Assignment getObjectDesriptionAssignment_3() { return cObjectDesriptionAssignment_3; }

		//[ObjectDescription]
		public CrossReference getObjectDesriptionObjectDescriptionCrossReference_3_0() { return cObjectDesriptionObjectDescriptionCrossReference_3_0; }

		//ID
		public RuleCall getObjectDesriptionObjectDescriptionIDTerminalRuleCall_3_0_1() { return cObjectDesriptionObjectDescriptionIDTerminalRuleCall_3_0_1; }
	}

	public class JavaCodeOrIDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JavaCodeOrID");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cJavaKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cColonKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cCodeAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cCodeSTRINGTerminalRuleCall_0_2_0 = (RuleCall)cCodeAssignment_0_2.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		
		//JavaCodeOrID:
		//	"java" ":" code=STRING | id=ID;
		public ParserRule getRule() { return rule; }

		//"java" ":" code=STRING | id=ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//"java" ":" code=STRING
		public Group getGroup_0() { return cGroup_0; }

		//"java"
		public Keyword getJavaKeyword_0_0() { return cJavaKeyword_0_0; }

		//":"
		public Keyword getColonKeyword_0_1() { return cColonKeyword_0_1; }

		//code=STRING
		public Assignment getCodeAssignment_0_2() { return cCodeAssignment_0_2; }

		//STRING
		public RuleCall getCodeSTRINGTerminalRuleCall_0_2_0() { return cCodeSTRINGTerminalRuleCall_0_2_0; }

		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }
	}

	public class ObjectManyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectMany");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cOptionObjectMaybeInnerParserRuleCall_0_0 = (RuleCall)cOptionAssignment_0.eContents().get(0);
		private final Keyword cAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		////Type:
		////  'boolean' | 'short' | 'int' | 'long' | 'float' | 'double' | 'char' | 'String'  | 'byte'
		////;
		//ObjectMany:
		//	option=ObjectMaybeInner "*";
		public ParserRule getRule() { return rule; }

		//option=ObjectMaybeInner "*"
		public Group getGroup() { return cGroup; }

		//option=ObjectMaybeInner
		public Assignment getOptionAssignment_0() { return cOptionAssignment_0; }

		//ObjectMaybeInner
		public RuleCall getOptionObjectMaybeInnerParserRuleCall_0_0() { return cOptionObjectMaybeInnerParserRuleCall_0_0; }

		//"*"
		public Keyword getAsteriskKeyword_1() { return cAsteriskKeyword_1; }
	}

	public class ObjectChoiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectChoice");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOptionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOptionsObjectMaybeInnerParserRuleCall_1_0 = (RuleCall)cOptionsAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cVerticalLineKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cOptionsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cOptionsObjectMaybeInnerParserRuleCall_2_1_0 = (RuleCall)cOptionsAssignment_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ObjectChoice:
		//	"(" options+=ObjectMaybeInner ("|" options+=ObjectMaybeInner)* ")";
		public ParserRule getRule() { return rule; }

		//"(" options+=ObjectMaybeInner ("|" options+=ObjectMaybeInner)* ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//options+=ObjectMaybeInner
		public Assignment getOptionsAssignment_1() { return cOptionsAssignment_1; }

		//ObjectMaybeInner
		public RuleCall getOptionsObjectMaybeInnerParserRuleCall_1_0() { return cOptionsObjectMaybeInnerParserRuleCall_1_0; }

		//("|" options+=ObjectMaybeInner)*
		public Group getGroup_2() { return cGroup_2; }

		//"|"
		public Keyword getVerticalLineKeyword_2_0() { return cVerticalLineKeyword_2_0; }

		//options+=ObjectMaybeInner
		public Assignment getOptionsAssignment_2_1() { return cOptionsAssignment_2_1; }

		//ObjectMaybeInner
		public RuleCall getOptionsObjectMaybeInnerParserRuleCall_2_1_0() { return cOptionsObjectMaybeInnerParserRuleCall_2_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}

	public class ObjectMaybeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectMaybe");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cOptionAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final CrossReference cOptionObjectDescriptionCrossReference_0_0 = (CrossReference)cOptionAssignment_0.eContents().get(0);
		private final RuleCall cOptionObjectDescriptionIDTerminalRuleCall_0_0_1 = (RuleCall)cOptionObjectDescriptionCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cDescriptionAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cDescriptionObjectMaybeInnerParserRuleCall_1_0_0 = (RuleCall)cDescriptionAssignment_1_0.eContents().get(0);
		private final Keyword cQuestionMarkKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//ObjectMaybe:
		//	option=[ObjectDescription] | description=ObjectMaybeInner "?";
		public ParserRule getRule() { return rule; }

		//option=[ObjectDescription] | description=ObjectMaybeInner "?"
		public Alternatives getAlternatives() { return cAlternatives; }

		//option=[ObjectDescription]
		public Assignment getOptionAssignment_0() { return cOptionAssignment_0; }

		//[ObjectDescription]
		public CrossReference getOptionObjectDescriptionCrossReference_0_0() { return cOptionObjectDescriptionCrossReference_0_0; }

		//ID
		public RuleCall getOptionObjectDescriptionIDTerminalRuleCall_0_0_1() { return cOptionObjectDescriptionIDTerminalRuleCall_0_0_1; }

		//description=ObjectMaybeInner "?"
		public Group getGroup_1() { return cGroup_1; }

		//description=ObjectMaybeInner
		public Assignment getDescriptionAssignment_1_0() { return cDescriptionAssignment_1_0; }

		//ObjectMaybeInner
		public RuleCall getDescriptionObjectMaybeInnerParserRuleCall_1_0_0() { return cDescriptionObjectMaybeInnerParserRuleCall_1_0_0; }

		//"?"
		public Keyword getQuestionMarkKeyword_1_1() { return cQuestionMarkKeyword_1_1; }
	}

	public class ObjectMaybeInnerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ObjectMaybeInner");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cObjectNextParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cObjectNodeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cObjectAttributeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ObjectMaybeInner:
		//	ObjectNext | ObjectNode | ObjectAttribute;
		public ParserRule getRule() { return rule; }

		//ObjectNext | ObjectNode | ObjectAttribute
		public Alternatives getAlternatives() { return cAlternatives; }

		//ObjectNext
		public RuleCall getObjectNextParserRuleCall_0() { return cObjectNextParserRuleCall_0; }

		//ObjectNode
		public RuleCall getObjectNodeParserRuleCall_1() { return cObjectNodeParserRuleCall_1; }

		//ObjectAttribute
		public RuleCall getObjectAttributeParserRuleCall_2() { return cObjectAttributeParserRuleCall_2; }
	}

	public class KeywordElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Keyword");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cNameKeyKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cNameValueKeyword_1_0 = (Keyword)cNameAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Keyword:
		//	name="Key" | name="Value" | name=ID;
		public ParserRule getRule() { return rule; }

		//name="Key" | name="Value" | name=ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//name="Key"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"Key"
		public Keyword getNameKeyKeyword_0_0() { return cNameKeyKeyword_0_0; }

		//name="Value"
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//"Value"
		public Keyword getNameValueKeyword_1_0() { return cNameValueKeyword_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
	}
	
	
	private final DTDSLElements pDTDSL;
	private final StartPointElements pStartPoint;
	private final AbstractElements pAbstract;
	private final StringDescriptionElements pStringDescription;
	private final StringDescriptionInnerElements pStringDescriptionInner;
	private final StringRuleElements pStringRule;
	private final StringOverReadElements pStringOverRead;
	private final StringKeyElements pStringKey;
	private final StringValueElements pStringValue;
	private final ObjectDescriptionElements pObjectDescription;
	private final ObjectNodeTypeElements pObjectNodeType;
	private final ObjectDescriptionInnerElements pObjectDescriptionInner;
	private final ObjectAttributeElements pObjectAttribute;
	private final QualifiedNameElements pQualifiedName;
	private final ObjectNodeElements pObjectNode;
	private final ObjectNextElements pObjectNext;
	private final JavaCodeOrIDElements pJavaCodeOrID;
	private final ObjectManyElements pObjectMany;
	private final ObjectChoiceElements pObjectChoice;
	private final ObjectMaybeElements pObjectMaybe;
	private final ObjectMaybeInnerElements pObjectMaybeInner;
	private final KeywordElements pKeyword;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DTDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDTDSL = new DTDSLElements();
		this.pStartPoint = new StartPointElements();
		this.pAbstract = new AbstractElements();
		this.pStringDescription = new StringDescriptionElements();
		this.pStringDescriptionInner = new StringDescriptionInnerElements();
		this.pStringRule = new StringRuleElements();
		this.pStringOverRead = new StringOverReadElements();
		this.pStringKey = new StringKeyElements();
		this.pStringValue = new StringValueElements();
		this.pObjectDescription = new ObjectDescriptionElements();
		this.pObjectNodeType = new ObjectNodeTypeElements();
		this.pObjectDescriptionInner = new ObjectDescriptionInnerElements();
		this.pObjectAttribute = new ObjectAttributeElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pObjectNode = new ObjectNodeElements();
		this.pObjectNext = new ObjectNextElements();
		this.pJavaCodeOrID = new JavaCodeOrIDElements();
		this.pObjectMany = new ObjectManyElements();
		this.pObjectChoice = new ObjectChoiceElements();
		this.pObjectMaybe = new ObjectMaybeElements();
		this.pObjectMaybeInner = new ObjectMaybeInnerElements();
		this.pKeyword = new KeywordElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.wbg.DTDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DTDSL:
	//	"parserName" "=" parserName=STRING ";" "parserType" "=" type=("javaObject" | "string") ";" objDescription+=Abstract*
	//	start=StartPoint;
	public DTDSLElements getDTDSLAccess() {
		return pDTDSL;
	}
	
	public ParserRule getDTDSLRule() {
		return getDTDSLAccess().getRule();
	}

	//StartPoint:
	//	"beginWith" "=" begin=[ObjectDescription] | begin=[StringDescription] ";";
	public StartPointElements getStartPointAccess() {
		return pStartPoint;
	}
	
	public ParserRule getStartPointRule() {
		return getStartPointAccess().getRule();
	}

	//Abstract:
	//	ObjectDescription | //| ObjectHashMapDescription
	//	StringDescription;
	public AbstractElements getAbstractAccess() {
		return pAbstract;
	}
	
	public ParserRule getAbstractRule() {
		return getAbstractAccess().getRule();
	}

	////---------------------------  String  ---------------------------
	//StringDescription:
	//	"String" name=ID ":" "{" description+=StringDescriptionInner* "}";
	public StringDescriptionElements getStringDescriptionAccess() {
		return pStringDescription;
	}
	
	public ParserRule getStringDescriptionRule() {
		return getStringDescriptionAccess().getRule();
	}

	//StringDescriptionInner: //	rule+=StringRule+
	//	StringOverRead | StringKey | StringValue;
	public StringDescriptionInnerElements getStringDescriptionInnerAccess() {
		return pStringDescriptionInner;
	}
	
	public ParserRule getStringDescriptionInnerRule() {
		return getStringDescriptionInnerAccess().getRule();
	}

	//StringRule:
	//	StringOverRead | StringKey | StringValue;
	public StringRuleElements getStringRuleAccess() {
		return pStringRule;
	}
	
	public ParserRule getStringRuleRule() {
		return getStringRuleAccess().getRule();
	}

	//StringOverRead:
	//	STRING;
	public StringOverReadElements getStringOverReadAccess() {
		return pStringOverRead;
	}
	
	public ParserRule getStringOverReadRule() {
		return getStringOverReadAccess().getRule();
	}

	//StringKey:
	//	"Key";
	public StringKeyElements getStringKeyAccess() {
		return pStringKey;
	}
	
	public ParserRule getStringKeyRule() {
		return getStringKeyAccess().getRule();
	}

	//StringValue:
	//	"Value";
	public StringValueElements getStringValueAccess() {
		return pStringValue;
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}

	////---------------------------  Object  ---------------------------
	////ObjectHashMapDescription:
	////	name=ID 'as' 'HashMap' ':' '{' description=ObjectHashMapDescriptionInner '}'
	////;
	////
	////ObjectHashMapDescriptionInner:
	////	
	////;
	//ObjectDescription:
	//	"Node" name=ID ":" "{" description+=ObjectDescriptionInner* "}";
	public ObjectDescriptionElements getObjectDescriptionAccess() {
		return pObjectDescription;
	}
	
	public ParserRule getObjectDescriptionRule() {
		return getObjectDescriptionAccess().getRule();
	}

	//ObjectNodeType:
	//	"Node" | "Attribute";
	public ObjectNodeTypeElements getObjectNodeTypeAccess() {
		return pObjectNodeType;
	}
	
	public ParserRule getObjectNodeTypeRule() {
		return getObjectNodeTypeAccess().getRule();
	}

	//ObjectDescriptionInner:
	//	(ObjectNode | ObjectAttribute | ObjectNext | ObjectMaybe | ObjectMany | ObjectChoice) ";";
	public ObjectDescriptionInnerElements getObjectDescriptionInnerAccess() {
		return pObjectDescriptionInner;
	}
	
	public ParserRule getObjectDescriptionInnerRule() {
		return getObjectDescriptionInnerAccess().getRule();
	}

	////ObjectAttribute:
	////	'hasAttribute' attributes=ID 'ofType' types=Type 
	////;
	//ObjectAttribute:
	//	"hasAttribute" attributes=ID ("as" stringMethode=[StringDescription])? // 'ofType' types=[jvmTypes::JvmType | QualifiedName] 
	//;
	public ObjectAttributeElements getObjectAttributeAccess() {
		return pObjectAttribute;
	}
	
	public ParserRule getObjectAttributeRule() {
		return getObjectAttributeAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	////ObjectAttribute:
	////	'hasAttribute' attributes=ID 'ofType' (types=Type | inner=[ObjectDescription])
	////;
	////ObjectNode:
	////	'hasNode' attributes=ID 'ofType' (types=Type 'as' keyword=Keyword | inner=[ObjectDescription]) ';'	
	////;
	//ObjectNode:
	//	"hasNode" attributes=ID "as" inner=[ObjectDescription];
	public ObjectNodeElements getObjectNodeAccess() {
		return pObjectNode;
	}
	
	public ParserRule getObjectNodeRule() {
		return getObjectNodeAccess().getRule();
	}

	//ObjectNext:
	//	"hasNext" attribute=JavaCodeOrID "as" objectDesription=[ObjectDescription];
	public ObjectNextElements getObjectNextAccess() {
		return pObjectNext;
	}
	
	public ParserRule getObjectNextRule() {
		return getObjectNextAccess().getRule();
	}

	//JavaCodeOrID:
	//	"java" ":" code=STRING | id=ID;
	public JavaCodeOrIDElements getJavaCodeOrIDAccess() {
		return pJavaCodeOrID;
	}
	
	public ParserRule getJavaCodeOrIDRule() {
		return getJavaCodeOrIDAccess().getRule();
	}

	////Type:
	////  'boolean' | 'short' | 'int' | 'long' | 'float' | 'double' | 'char' | 'String'  | 'byte'
	////;
	//ObjectMany:
	//	option=ObjectMaybeInner "*";
	public ObjectManyElements getObjectManyAccess() {
		return pObjectMany;
	}
	
	public ParserRule getObjectManyRule() {
		return getObjectManyAccess().getRule();
	}

	//ObjectChoice:
	//	"(" options+=ObjectMaybeInner ("|" options+=ObjectMaybeInner)* ")";
	public ObjectChoiceElements getObjectChoiceAccess() {
		return pObjectChoice;
	}
	
	public ParserRule getObjectChoiceRule() {
		return getObjectChoiceAccess().getRule();
	}

	//ObjectMaybe:
	//	option=[ObjectDescription] | description=ObjectMaybeInner "?";
	public ObjectMaybeElements getObjectMaybeAccess() {
		return pObjectMaybe;
	}
	
	public ParserRule getObjectMaybeRule() {
		return getObjectMaybeAccess().getRule();
	}

	//ObjectMaybeInner:
	//	ObjectNext | ObjectNode | ObjectAttribute;
	public ObjectMaybeInnerElements getObjectMaybeInnerAccess() {
		return pObjectMaybeInner;
	}
	
	public ParserRule getObjectMaybeInnerRule() {
		return getObjectMaybeInnerAccess().getRule();
	}

	//Keyword:
	//	name="Key" | name="Value" | name=ID;
	public KeywordElements getKeywordAccess() {
		return pKeyword;
	}
	
	public ParserRule getKeywordRule() {
		return getKeywordAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
