/*
 * generated by Xtext
 */
package de.wbg.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.wbg.ui.internal.DTDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DTDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DTDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DTDSLActivator.getInstance().getInjector(DTDSLActivator.DE_WBG_DTDSL);
	}
	
}
